In [1]:
listThree = list(range(1,4))
listTwo = list(range(1,4))
listSum = []

for index in range(3):
        listTwo[index] = listTwo[index] ** 2
        listThree[index] = listThree[index] ** 3
        listSum.append(listTwo[index] + listThree[index])
print(listSum)

[2, 12, 36]


In [3]:
import numpy as np
array_two = np.arange(1, 4) ** 2
array_three = np.arange(1,4) ** 3
print(array_two + array_three)

[ 2 12 36]


In [5]:
print(np.power(np.array([1,2,3]), 4))

[ 1 16 81]


In [2]:
import numpy as np
x = np.arange(3)
y = np.arange(3)
z = np.arange(3)
multi_array = np.array([x, y, z ])
print(multi_array)

[[0 1 2]
 [0 1 2]
 [0 1 2]]


In [4]:
w = np.linspace(1,10, 100)
print(w)

[ 1.          1.09090909  1.18181818  1.27272727  1.36363636  1.45454545
  1.54545455  1.63636364  1.72727273  1.81818182  1.90909091  2.
  2.09090909  2.18181818  2.27272727  2.36363636  2.45454545  2.54545455
  2.63636364  2.72727273  2.81818182  2.90909091  3.          3.09090909
  3.18181818  3.27272727  3.36363636  3.45454545  3.54545455  3.63636364
  3.72727273  3.81818182  3.90909091  4.          4.09090909  4.18181818
  4.27272727  4.36363636  4.45454545  4.54545455  4.63636364  4.72727273
  4.81818182  4.90909091  5.          5.09090909  5.18181818  5.27272727
  5.36363636  5.45454545  5.54545455  5.63636364  5.72727273  5.81818182
  5.90909091  6.          6.09090909  6.18181818  6.27272727  6.36363636
  6.45454545  6.54545455  6.63636364  6.72727273  6.81818182  6.90909091
  7.          7.09090909  7.18181818  7.27272727  7.36363636  7.45454545
  7.54545455  7.63636364  7.72727273  7.81818182  7.90909091  8.
  8.09090909  8.18181818  8.27272727  8.36363636  8.45454545  8.545

In [5]:
import numpy as np
x = np.arange(1, 10)
print(x)

[1 2 3 4 5 6 7 8 9]


In [6]:
print(x[2:7:2])

[3 5 7]


In [10]:
x = np.arange(9).reshape(3, -1)
print(x)
y = np.arange(18).reshape(2,3,3)
print(y)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]]
